// /!\ /!\ /!\ AUTOGENERATED FILE - DO NOT MODIFY MANUALLY /!\ /!\ /!\

import type { DefaultTheme } from "vitepress";
export default {
  "/book": [
    {
      "base": "/book",
      "text": "Book",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "✅⭐️ Nos Etoiles Contraires",
          "link": "/the-fault-in-our-stars"
        }
      ]
    }
  ],
  "/dev": [
    {
      "base": "/dev",
      "text": "Dev",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Breakout",
          "link": "/breakout"
        }
      ]
    }
  ],
  "/game": [
    {
      "base": "/game",
      "text": "Game",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "base": "/game/action",
          "text": "Action",
          "items": [
            {
              "text": "✅⭐️ Kingdom Hearts",
              "link": "/kingdom-hearts"
            }
          ]
        },
        {
          "base": "/game/rpg",
          "text": "Rpg",
          "items": [
            {
              "text": "✅⭐️ Pokemon Argent",
              "link": "/pokemon-silver"
            }
          ]
        },
        {
          "text": "Tlou",
          "link": "/tlou"
        }
      ]
    }
  ],
  "/manga": [
    {
      "base": "/manga",
      "text": "Manga",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Naruto",
          "link": "/naruto"
        },
        {
          "text": "One-piece",
          "link": "/one-piece"
        }
      ]
    }
  ],
  "/movie": [
    {
      "base": "/movie",
      "text": "Movie",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Arrival",
          "link": "/arrival"
        }
      ]
    }
  ],
  "/music": [
    {
      "base": "/music",
      "text": "Music",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Colors",
          "link": "/colors"
        }
      ]
    }
  ]
} satisfies DefaultTheme.Sidebar