// /!\ /!\ /!\ AUTOGENERATED FILE - DO NOT MODIFY MANUALLY /!\ /!\ /!\

import type { DefaultTheme } from "vitepress";
export default {
  "/anime": [
    {
      "base": "/anime",
      "text": "Anime",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Bleach",
          "link": "/bleach"
        },
        {
          "text": "Get Backers",
          "link": "/get-backers"
        },
        {
          "text": "Naruto",
          "link": "/naruto"
        },
        {
          "text": "One Piece",
          "link": "/one-piece"
        }
      ]
    }
  ],
  "/book": [
    {
      "base": "/book",
      "text": "Book",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "A Man called Ove",
          "link": "/a-man-called-ove"
        },
        {
          "text": "Fils des brumes",
          "link": "/mistborn"
        },
        {
          "text": "✅⭐️ Nos Etoiles Contraires",
          "link": "/the-fault-in-our-stars"
        }
      ]
    }
  ],
  "/dev": [
    {
      "base": "/dev",
      "text": "Programming",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "base": "/dev/algo",
          "text": "Algo",
          "items": [
            {
              "text": "Index",
              "link": "/index"
            }
          ]
        },
        {
          "base": "/dev/blog",
          "text": "Blog",
          "items": [
            {
              "text": "Index",
              "link": "/index"
            }
          ]
        },
        {
          "base": "/dev/lang",
          "text": "Lang",
          "items": [
            {
              "text": "Typescript",
              "link": "/typescript"
            }
          ]
        },
        {
          "base": "/dev/tools",
          "text": "Tools",
          "items": [
            {
              "text": "Index",
              "link": "/index"
            }
          ]
        },
        {
          "text": "🚧 Breakout",
          "link": "/breakout"
        },
        {
          "text": "Git",
          "link": "/git"
        },
        {
          "text": "JACK compiler",
          "link": "/jack-compiler"
        },
        {
          "text": "Tiny renderer",
          "link": "/tiny-renderer"
        }
      ]
    }
  ],
  "/game": [
    {
      "base": "/game",
      "text": "Game",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "base": "/game/action",
          "text": "Action",
          "items": [
            {
              "text": "✅⭐️ Kingdom Hearts",
              "link": "/kingdom-hearts"
            },
            {
              "text": "Sekiro",
              "link": "/sekiro"
            }
          ]
        },
        {
          "base": "/game/rpg",
          "text": "Rpg",
          "items": [
            {
              "text": "✅⭐️ Pokemon Argent",
              "link": "/pokemon-silver"
            }
          ]
        },
        {
          "text": "✅⭐️ The Last of Us",
          "link": "/tlou"
        }
      ]
    }
  ],
  "/japanese": [
    {
      "base": "/japanese",
      "text": "Japanese",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        }
      ]
    }
  ],
  "/manga": [
    {
      "base": "/manga",
      "text": "Manga",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "✅ Naruto",
          "link": "/naruto"
        },
        {
          "text": "🔄⏳📅 One Piece",
          "link": "/one-piece"
        }
      ]
    }
  ],
  "/movie": [
    {
      "base": "/movie",
      "text": "Movie",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "✅ The Arrival",
          "link": "/arrival"
        },
        {
          "text": "Harry Potter",
          "link": "/harry-potter"
        }
      ]
    }
  ],
  "/music": [
    {
      "base": "/music",
      "text": "Music",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Blooming in the mud",
          "link": "/blooming-in-the-mud"
        },
        {
          "text": "✅ Colors",
          "link": "/colors"
        }
      ]
    }
  ],
  "/series": [
    {
      "base": "/series",
      "text": "Series",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        },
        {
          "text": "Brookly 99",
          "link": "/brooklyn-99"
        },
        {
          "text": "Friends",
          "link": "/friends"
        },
        {
          "text": "How I met your Mother",
          "link": "/himym"
        },
        {
          "text": "Suits",
          "link": "/suits"
        }
      ]
    }
  ],
  "/travel": [
    {
      "base": "/travel",
      "text": "Travel",
      "items": [
        {
          "text": "Index",
          "link": "/index"
        }
      ]
    }
  ]
} satisfies DefaultTheme.Sidebar